#!/bin/bash

echo "🔧 Database Fix Script for Server"
echo "================================="

echo "📋 Step 1: Copy this script to your server"
echo "scp fix-database.sh user@server:/var/www/RealEstateCRMBackend/"
echo ""

echo "📋 Step 2: Run these commands on your server:"
echo ""
echo "cd /var/www/RealEstateCRMBackend/server"
echo ""
echo "# Check current database status"
echo "echo '🔍 Checking migration status...'"
echo "npx prisma migrate status"
echo ""
echo "# Check if table exists"
echo "echo '🔍 Checking if UserEmailSettings table exists...'"
echo "npx prisma db execute --stdin <<< \"SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'UserEmailSettings';\""
echo ""
echo "# Apply migrations"
echo "echo '📦 Applying migrations...'"
echo "npx prisma migrate deploy"
echo ""
echo "# Generate Prisma client"
echo "echo '⚙️  Generating Prisma client...'"
echo "npx prisma generate"
echo ""
echo "# Verify table creation"
echo "echo '✅ Verifying table creation...'"
echo "npx prisma db execute --stdin <<< \"SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'UserEmailSettings';\""
echo ""
echo "# Restart PM2"
echo "echo '🔄 Restarting PM2 processes...'"
echo "pm2 restart all"
echo ""
echo "echo '🎉 Database fix completed!'"
